on:
  # push:
  #   branches:
  #     - master
  workflow_dispatch:

permissions:
  contents: write
  id-token: write  # Required for OIDC
  issues: write
  packages: write
  pull-requests: write

name: Release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Semantic Release Action
        # You may pin to the exact commit or the version.
        # uses: codfish/semantic-release-action@cbd853afe12037afb1306caca9d6b1ab6a58cf2a
        # uses: codfish/semantic-release-action@v3# Recommended: Docker image digest from GitHub Container Registry (best for speed & security)
        uses: docker://ghcr.io/codfish/semantic-release-action@sha256:4c0955361cf42e5ab9bb05df3a1e2a781c443f9760b63a68957689445051a2fb

        with:
          # Define the list of plugins to use. Plugins will run in series, in the order defined, for each steps if they implement it.
          # https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#plugins
          additional-packages: |
            ['conventional-changelog-conventionalcommits@6', '@semantic-release/changelog', '@semantic-release/git']
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

          # This is used to set the author and committer information for semantic release commits
          # If environment variables are not set, committer will be in the name of Semantic Release Bot instead of the GitHub Actions bot
          GIT_AUTHOR_NAME: "github-actions[bot]"
          GIT_AUTHOR_EMAIL: "github-actions[bot]@users.noreply.github.com"
          GIT_COMMITTER_NAME: "github-actions[bot]"
          GIT_COMMITTER_EMAIL: "github-actions[bot]@users.noreply.github.com"
